### ISSUE TITLE
Bug in conjunction with Autodrive

### ISSUE THREAD

**Issue by 0scarZulu** [MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA#51]
![image](https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/assets/78980660/86678aea-9ba8-4b52-8845-285f9aafe559)

The vehicle cannot start (presumably battery flat) and is still moved by Autodrive. Speedometer pointer remains at 0. 
I also wonder why the battery is flat again. The vehicle is parked with the lights off. It feels like I have to charge the vehicle every day.

**Comment by MathiasHun** [comment]
This error may have already been corrected here
Changelog 0.8.6.3:

github <a href="https://github.com/MathiasHun/FS22_Real_Vehicle_Breakdowns_BETA/issues/40">issues#40</a> - After AI finish the work battery continue drops until goes empty

**Comment by 0scarZulu** [comment]
No, it is not. I am using the current version and the error persists. Everything written above is with the 0.8.6.3 


Also that it is not blocked but can still be driven by AD even though the battery is empty. Also the starter sound bends over the entire map.

**Comment by astro80** [comment]
> No, it is not. I am using the current version and the error persists. Everything written above is with the 0.8.6.3
> 
> Also that it is not blocked but can still be driven by AD even though the battery is empty. Also the starter sound bends over the entire map.

Same for me with the last version.
